version : 2

seeds:
 - name: employee
   description: a manual map of employees to customers
   columns:
        - name: employee_id
        tests:
            - unique
            - not_null
